[tool.poetry]
name = "pleiades"
version = "0.1.1"  # placeholder, version is handled by versioningit
description = "PLEIADES - Python Libraries Extensions for Isotopic Analysis via Detailed Examination of SAMMY"
authors = ["Alex M. Long <alexlong@lanl.gov>"]
license = "MIT"
packages = [
    { include = "pleiades", from = "src" }
]
include = [
    "nucDataLibs/**/*"
]

# ---------------------------------------------------------- #
# This section is for users who want to install via `poetry` #
# ---------------------------------------------------------- #
[tool.poetry.dependencies]
# Core
python = "^3.10"  # replace with the appropriate Python version
setuptools = "*"
# Numerical
numpy = "*"
scipy = "*"
pandas = "*"
# Visualization
matplotlib = ">=3.1.2"

[tool.poetry.scripts]
pleiades = "pleiades:main"  # Console script entry point

[build-system]
requires = ["poetry>=1.1.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dev-dependencies]
pytest = "*"
pre-commit = "^4.0.1"

# --------------------------------------------- #
# The rest all 3rd party plugins configurations #
# --------------------------------------------- #
